fix for issue #60: created logout view
opencodeiiita/Forum-Backend pull request #63
Opened 2022-12-28 07:16 UTC by MistyRavager

Issue: 60
Description:
Created logout view

2022-12-29 06:28 UTC, TheRealSibasishBehera requested changes
you should use a `get` method ,and delete the `auth_token` from user , then `logout` the user and then send a Response , with a 200 status code

2022-12-29 10:56 UTC, MistyRavager commented
updated changes: used get, request, deleted token, sent a success response

2022-12-30 04:48 UTC, TheRealSibasishBehera approved these changes

2022-12-30 04:49 UTC, TheRealSibasishBehera commented
Thanks

2022-12-30 04:49 UTC, merged